name: CI

on:
  push:
    branches:
      # This is where pull requests from "bors r+" are built.
      - staging
      # This is where pull requests from "bors try" are built.
      - trying
      # Build master branch.
      - master

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      matrix:
        version:
          - '1.3'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        arch:
          - x64
          - x86
        include:
          - version: '1'
            os: ubuntu-latest
            arch: x64
            coverage: true
        exclude:
          - os: ubuntu-latest
            arch: x86
          - os: macOS-latest
            arch: x86
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: ${{ matrix.arch }}
      # Limitation of pip: https://pythonot.github.io/index.html#pip-installation
      - run: python -m pip install cython numpy
      - run: python -m pip install pot
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@latest
        env:
          PYTHON: python
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
        if: matrix.coverage
      - uses: codecov/codecov-action@v1
        if: matrix.coverage
        with:
          file: lcov.info
      - uses: coverallsapp/github-action@master
        if: matrix.coverage
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
