name: CompatHelper
on:
  schedule:
    - cron: '00 00 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        run: julia -e 'using CompatHelper; CompatHelper.main(; subdirs = ["", "test"])'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
